/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Dominio.CalculoGastoCalorico;
import Dominio.CalculoImc;
import Dominio.Validador;

import javax.swing.*;

/**
 *
 * @author Guido
 */
public class TelaGastoCalorico extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName());

    /**
     * Creates new form TelaGastoCalorico
     */
    public TelaGastoCalorico() {

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioHomem = new javax.swing.JRadioButton();
        jRadioMulher = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        comboAtividade = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtResultadoBasal = new javax.swing.JTextField();
        txtResultadoGeral = new javax.swing.JTextField();
        bntVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gasto Calórico");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cálculo de Gasto Calórico"));

        jRadioHomem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioHomem.setText("Homem");
        jRadioHomem.addItemListener(this::jRadioHomemItemStateChanged);

        jRadioMulher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioMulher.setText("Mulher");
        jRadioMulher.addItemListener(this::jRadioMulherItemStateChanged);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Peso (kg):");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Altura (cm):");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Idade:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nível de atividade:");

        comboAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{" ", "Sedentário", "Leve (1 a 3 dias/semana)", "Moderado (3 a 5 dias/semana)", "Ativo (5 a 6 dias/semana)", "Extremamente ativo (exercícios diários)"}));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(txtPeso)
                                                                        .addComponent(txtAltura)
                                                                        .addComponent(txtIdade, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jRadioMulher)
                                                                                .addGap(57, 57, 57)
                                                                                .addComponent(jRadioHomem))
                                                                        .addComponent(jLabel4))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(6, 6, 6))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(comboAtividade, 0, 290, Short.MAX_VALUE)
                                                .addContainerGap())))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCalcular)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioMulher)
                                        .addComponent(jRadioHomem))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCalcular)
                                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Gasto Basal:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Gasto Total:");

        bntVoltar.setText("< Voltar");
        bntVoltar.addActionListener(this::bntVoltarActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtResultadoBasal)
                                        .addComponent(txtResultadoGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntVoltar)
                                .addGap(115, 115, 115))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtResultadoBasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtResultadoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(bntVoltar)
                                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioMulherItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioMulherItemStateChanged
        if (jRadioMulher.isSelected() == true) jRadioHomem.setSelected(false);
    }//GEN-LAST:event_jRadioMulherItemStateChanged

    private void jRadioHomemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioHomemItemStateChanged
        if (jRadioHomem.isSelected() == true) jRadioMulher.setSelected(false);
    }//GEN-LAST:event_jRadioHomemItemStateChanged

    private void bntVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_bntVoltarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        CalculoGastoCalorico calculoCalorico = new CalculoGastoCalorico();
        Validador validador = new Validador();

        String strPeso = txtPeso.getText();
        String strAltura = txtAltura.getText();
        String strIdade = txtIdade.getText();
        String strCombo = comboAtividade.getSelectedItem().toString();

        if (jRadioMulher.isSelected() == false && jRadioHomem.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Por favor, escolha um dos sexos.");
        } else if (strPeso.isEmpty() || strIdade.isEmpty() || strAltura.isEmpty() || strCombo.matches(" ")) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha os campos e escolha uma opção de atividade.");
        } else {
            if (jRadioHomem.isSelected() == true && jRadioMulher.isSelected() == false) {
                validador.validarPeso(strPeso);
                validador.validarAltura(strAltura);
                validador.validarIdade(strIdade);

                if (validador.validarPeso(strPeso) == false) {
                    JOptionPane.showMessageDialog(null, "Por favor digite o peso no formato 00.00 ou 000.00");
                    txtResultadoGeral.setText(String.valueOf(" "));
                    txtResultadoBasal.setText(String.valueOf(" "));
                } else if (validador.validarAltura(strAltura) == false) {
                    JOptionPane.showMessageDialog(null, "Por favor digite a altura no formato 0.00");
                    txtResultadoGeral.setText(String.valueOf(" "));
                    txtResultadoBasal.setText(String.valueOf(" "));
                } else if (validador.validarIdade(strIdade) == false) {
                    JOptionPane.showMessageDialog(null, "Por favor digite a idade no formato 00 ou 0");
                    txtResultadoGeral.setText(String.valueOf(" "));
                    txtResultadoBasal.setText(String.valueOf(" "));


                } else if (validador.validarNumerosPositivos(strIdade, strAltura, strPeso) == false) {
                    JOptionPane.showMessageDialog(null, "Por favor digite números acima de 0");
                    txtResultadoGeral.setText(String.valueOf(" "));
                    txtResultadoBasal.setText(String.valueOf(" "));
                } else {
                    calculoCalorico.calculoBalHomem(strPeso, strAltura, strIdade);
                    calculoCalorico.calculoGastoTotal(strCombo);

                    double resultCalBasal = calculoCalorico.getCalBasal();
                    double resultCalTotal = calculoCalorico.getCalTotal();

                    txtResultadoGeral.setText(String.valueOf(resultCalTotal));
                    txtResultadoBasal.setText(String.valueOf(resultCalBasal));
                }


            } else {
                validador.validarPeso(strPeso);
                validador.validarAltura(strAltura);
                validador.validarIdade(strIdade);

                if (validador.validarPeso(strPeso) == false) {
                    JOptionPane.showMessageDialog(null, "Por favor digite o peso no formato 00.00 ou 000.00");
                    txtResultadoGeral.setText(String.valueOf(" "));
                    txtResultadoBasal.setText(String.valueOf(" "));
                } else if (validador.validarAltura(strAltura) == false) {
                    JOptionPane.showMessageDialog(null, "Por favor digite a altura no formato 0.00");
                    txtResultadoGeral.setText(String.valueOf(" "));
                    txtResultadoBasal.setText(String.valueOf(" "));
                } else if (validador.validarIdade(strIdade) == false) {
                    JOptionPane.showMessageDialog(null, "Por favor digite a idade no formato 00 ou 0");
                    txtResultadoGeral.setText(String.valueOf(" "));
                    txtResultadoBasal.setText(String.valueOf(" "));


                } else if (validador.validarNumerosPositivos(strIdade, strAltura, strPeso) == false) {
                    JOptionPane.showMessageDialog(null, "Por favor digite números acima de 0");
                    txtResultadoGeral.setText(String.valueOf(" "));
                    txtResultadoBasal.setText(String.valueOf(" "));
                } else {
                    calculoCalorico.calculoBasalMulher(strPeso, strAltura, strIdade);
                    calculoCalorico.calculoGastoTotal(strCombo);

                    double resultCalBasal = calculoCalorico.getCalBasal();
                    double resultCalTotal = calculoCalorico.getCalTotal();

                    txtResultadoGeral.setText(String.valueOf(String.format("%.2f", resultCalTotal)));
                    txtResultadoBasal.setText(String.valueOf(String.format("%.2f", resultCalBasal)));
                }


            }
        }


    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaGastoCalorico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVoltar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> comboAtividade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioHomem;
    private javax.swing.JRadioButton jRadioMulher;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtResultadoBasal;
    private javax.swing.JTextField txtResultadoGeral;
    // End of variables declaration//GEN-END:variables
}
